#!/bin/bash

echo "================================"
echo "上传项目到 GitHub 步骤："
echo "================================"
echo ""
echo "1. 访问 https://github.com/new 创建新仓库"
echo "   - 仓库名称: review-sorting-system"
echo "   - 不要勾选 'Add a README file'"
echo "   - 点击 'Create repository'"
echo ""
echo "2. 复制你的 GitHub 仓库 URL（例如：https://github.com/你的用户名/review-sorting-system.git）"
echo ""
echo "3. 运行以下命令（替换 YOUR_REPO_URL）："
echo ""
echo "   cd review-sorting-system"
echo "   git remote add origin YOUR_REPO_URL"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "================================"
